# for local development
version: '3.7'
services:
  quasar:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '8080:8080'
    volumes:
    - '.:/app'
    - '/app/node_modules'  # Agregamos este volumen para evitar sobrescribir node_modules en el contenedor
    command: "quasar dev"